# Generated by Django 2.1.5 on 2019-01-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFMainBackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Actor',
        ),
    ]
