# Generated by Django 2.1.5 on 2019-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFMainBackend', '0002_auto_20190105_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='headshot',
            field=models.ImageField(upload_to='./static'),
        ),
    ]
