# Generated by Django 2.1.5 on 2019-01-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFMainBackend', '0003_auto_20190105_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='headshot',
            field=models.ImageField(upload_to='images'),
        ),
    ]
