# Generated by Django 2.1.5 on 2019-01-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFMainBackend', '0004_auto_20190105_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
