# Generated by Django 2.1.5 on 2019-01-05 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFMainBackend', '0005_auto_20190105_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFMainBackend.Actor')),
            ],
        ),
    ]
